---
- name: Deployment of web server
  hosts: web
  become: true
  tasks: 
    
    - name: Install Apache and Firwalld
      yum :
        name:
          - httpd
          - firewalld
        state: latest
    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Start Firewalld Service
      service:
        name: firewalld
        state: started
        enabled: true
    - name: Deploy web page
      copy:
        src: files.html
        dest: /var/www/html/index.html

    - name: Allow httpd on firewall
      firewalld:
        service: httpd
        immediate: true
        permanent: true
        state: enabled
      notify: 
        - restart httpd 
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
