---
- name: Deployment of web server
  hosts: web
  become: true
  tasks: 
    
    - name: Install Apache and Firwalld
      yum :
        name:
          - httpd
          - firewalld
          - git-all
        state: latest
    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Start Firewalld Service
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow httpd on firewall
      firewalld:
        port: 8080/tcp
        immediate: true
        permanent: true
        state: enabled

    - name: Deployment of Project on httpd
      git: 
        repo: "https://github.com/madhavdubey97/test.git"
        dest: /var/www/html  
